def define_required_columns():
    required_columns = [
        'Received Date/Time'
        ,'User ID'
        ,'Request Type'
        ,'Rx Case Number'
        ,'Auth Number'
        ,'Fax Forward #'
        ,'Template Type'
        ,'Member ID'
        ,'Routing'
        ,'UM LOB'
        ,'UM Case Priority'
        ,'RX LOB'
        ,'RX Case Priority'
        ,'Completed'
        ,'RX Case Status'
        ,'File Name'
        ,'Claim Datetime'
        ,'Request Completed Datetime'
        ,'Time Between Fax Received & Intake Completion'
        ,'Time Between Claiming Task & Intake Completion'
        ,'Received Date_Orig'
        ,'Completed Date'
        ,'Received Date_New'
        ,'File_Name'
        ,'File_Name_Unique'
        ,'File_Name_Count'
        ,'Month_Completed'
        ,'TotalTime_RecToCom'
        ,'TotalTime_ClaimToCom'
        ,'Day_Recd Orig'
        ,'Day_Recd New'
        ,'SOW'
        ,'Location'
        ,'TAT_RecdToCom'
        ,'TAT_ClaimToCom'
        ,'ReceivedTime'
        ,'Month_Received_New'
        ,'ReceivedDateTime_New'
        ,'Pass'
        ,'Fail'
        ,'Pass_Claim'
        ,'Fail_Claim'
        ,'CompletedDateTime_Actual'
        ,'CompletedDateTime_Expected'
        ,'Routing Queue'
        ,'RecdDate Validation'
        ,'Validation'
        ,'Month, Year'
        # ,'Month #'
        ,'File ID'
        ,'Counter'
        ,'Hour Bucket (Arrival)'
        ,'Correct Hour Bucket (Arrival)'
        ,'Hour Bucket (Processing)'
        ,'Correct Hour Bucket (Processing)'
        ,'Hour Type'
        ,'Target AHT (mins)'
        ,'Target Contractual Hours'
        ,'Hour Converter'
        ,'CPT Code'
        ,'Service Line'
    ]
    return required_columns